<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-1HND23K" name="TgTest" tests="1" failures="0" timestamp="8 Sep 2017 21:10:27 GMT" time="0.000" errors="1">
  <testcase name="testTgPositive" time="0.000" classname="TgTest">
    <error type="java.lang.Throwable" message="Method TgTest.testTgPositive(double, double)[pri:0, instance:TgTest@2a3046da] depends on not successfully finished methods in group &quot;sin/cos&quot;">
      <![CDATA[java.lang.Throwable: Method TgTest.testTgPositive(double, double)[pri:0, instance:TgTest@2a3046da] depends on not successfully finished methods in group "sin/cos"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1211)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at Runner.main(Runner.java:30)
]]>
    </error>
  </testcase> <!-- testTgPositive -->
</testsuite> <!-- TgTest -->
